# Generated by Django 4.2.7 on 2025-11-02 19:14

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('analyzer', '0002_alter_analysis_id_alter_job_id'),
    ]

    operations = [
        migrations.AddField(
            model_name='analysis',
            name='jd_keyword_freq',
            field=models.JSONField(default=dict),
        ),
        migrations.AddField(
            model_name='analysis',
            name='resume_keyword_freq',
            field=models.JSONField(default=dict),
        ),
        migrations.AddField(
            model_name='analysis',
            name='semantic_similarity',
            field=models.FloatField(default=0.0),
        ),
        migrations.AddField(
            model_name='analysis',
            name='skill_match_score',
            field=models.FloatField(default=0.0),
        ),
        migrations.AddField(
            model_name='analysis',
            name='suggestions',
            field=models.JSONField(default=list),
        ),
        migrations.CreateModel(
            name='ComparisonHistory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('score_difference', models.FloatField()),
                ('skill_difference', models.JSONField(default=dict)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('analysis1', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='comparison1', to='analyzer.analysis')),
                ('analysis2', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='comparison2', to='analyzer.analysis')),
            ],
        ),
    ]
